import fs from "fs-extra";
import path from "path";
import { fileURLToPath } from "url";
import { execa } from "execa";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function installDependencies(target) {
  console.log("📦 Installing dependencies...");

  // We'll rely on the template's package.json to declare deps. Use npm install there.
  await execa("npm", ["install"], { cwd: target, stdio: "inherit" });
}

export async function createProject(projectName, cssOption) {
  const target = path.join(process.cwd(), projectName);
  const templateRoot = path.join(__dirname, "templates", "base");

  if (await fs.pathExists(target)) {
    throw new Error(`Target directory "${target}" already exists`);
  }

  await fs.copy(templateRoot, target);

  // Update the template package.json's name and description
  const pkgPath = path.join(target, "package.json");
  const pkg = await fs.readJson(pkgPath);
  pkg.name = projectName;
  pkg.description =
    pkg.description || `A project generated by rp-react-template`;
  await fs.writeJson(pkgPath, pkg, { spaces: 2 });

  console.log(`✔ Project files copied to ${target}`);

  await installDependencies(target);

  // If user chose sass or less, install them and update files accordingly (basic)
  if (cssOption === "sass") {
    console.log("🔧 Adding sass dependency...");
    await execa("npm", ["install", "-D", "sass"], {
      cwd: target,
      stdio: "inherit",
    });
  } else if (cssOption === "less") {
    console.log("🔧 Adding less dependency...");
    await execa("npm", ["install", "-D", "less"], {
      cwd: target,
      stdio: "inherit",
    });
  }

  console.log("✔ Dependencies installed!");
}
